version: '3'
services:
  web:
    image: t8_dnhsscioly_backendv1
    build: .
    ports:
      - "8098:8098"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/t8_dnhsscioly_backend/volumes
